# Use the updated Playwright image with Node.js and browsers
FROM mcr.microsoft.com/playwright:v1.50.1-noble 

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000
CMD ["npm", "run", "start:dev"]